# Generated by Django 5.0.7 on 2024-07-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BirthdayForm',
            new_name='Birthday',
        ),
    ]
